export default defineAppConfig({
  colors: {
    primary: "#fff15a",
    primaryLight: "#fffbde",
    secondary: "#32fc74",
    secondaryLight: "#d6fee3",
    tertiary: "#6d49ff",
    tertiaryLight: "#cdbcff",
    dark: "#404040",
    light: "#f5f5f5",
  },
  colorsLoadingScreen: ["#6d49ff", "#fff15a", "#32fc74", "#fffbde", "#d6fee3"],
  colorSwatches: [
    { hex: "#6d49ff" },
    { hex: "#fff15a" },
    { hex: "#32fc74" },
    { hex: "#fffbde" },
    { hex: "#d6fee3" },
    { hex: "#404040" },
  ],
  strengths: [
    {
      category: "Strategic Thinking",
      strength: [
        { name: "Analytical" },
        { name: "Context" },
        { name: "Futuristic" },
        { name: "Ideation" },
        { name: "Input" },
        { name: "Intellection" },
        { name: "Learner" },
        { name: "Strategic" },
      ],
    },
    {
      category: "Influencing",
      strength: [
        { name: "Activator" },
        { name: "Command" },
        { name: "Communication" },
        { name: "Competition" },
        { name: "Maximizer" },
        { name: "Self-Assurance" },
        { name: "Significance" },
        { name: "Woo" },
      ],
    },
    {
      category: "Relationship Building",
      strength: [
        { name: "Adaptability" },
        { name: "Connectedness" },
        { name: "Developer" },
        { name: "Empathy" },
        { name: "Harmony" },
        { name: "Includer" },
        { name: "Individualization" },
        { name: "Positivity" },
        { name: "Relator" },
      ],
    },
    {
      category: "Executing",
      strength: [
        { name: "Achiever" },
        { name: "Arranger" },
        { name: "Belief" },
        { name: "Consistency" },
        { name: "Deliberative" },
        { name: "Discipline" },
        { name: "Focus" },
        { name: "Responsibility" },
        { name: "Restorative" },
      ],
    },
  ],
});
